version: '2'
services:
    y-app:
        image: y
        external_links:
            - y-mysql:mysql
            - y-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/y?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    y-mysql:
        extends:
            file: mysql.yml
            service: y-mysql
    y-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: y-elasticsearch
